const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', '..', 'deepseek-harness', 'packages', 'client', 'ui-primitives', 'src', 'icons', 'index.tsx');
const OUT = path.join(__dirname, '..', 'src', 'components', 'icons', 'OriginalIcons.tsx');

async function main() {
  const content = await fs.promises.readFile(SRC, 'utf8');
  
  // Split by export const Icon... pattern
  const parts = content.split(/\/\*\*[\s\S]*?\*\/\s*export const /);
  
  // First part is the header/imports
  const header = parts[0];
  
  const icons = [];
  for (let i = 1; i < parts.length; i++) {
    const part = parts[i];
    // Extract name (up to first =)
    const nameMatch = part.match(/^(\w+)\s*=/);
    if (!nameMatch) continue;
    const name = nameMatch[1];
    
    // Extract default size
    const sizeMatch = part.match(/size\s*=\s*(\d+)/);
    const defaultSize = sizeMatch ? parseInt(sizeMatch[1]) : 16;
    
    // Extract the full SVG (from <svg to </svg>)
    const svgMatch = part.match(/(<svg[\s\S]*?<\/svg>)/);
    if (!svgMatch) continue;
    const svg = svgMatch[1];
    
    icons.push({ name, defaultSize, svg });
  }
  
  console.log(`Extracted ${icons.length} icons`);
  
  let output = `/**
 * Original DeepSeek web version icons
 * Extracted from packages/client/ui-primitives/src/icons/index.tsx
 * Auto-generated by scripts/extract-icons.js
 */

interface IconProps {
  size?: number;
  className?: string;
}

`;
  
  for (const icon of icons) {
    // Replace the hardcoded size with {size} and add xmlns if missing
    let svg = icon.svg
      .replace(/width=\{size\}/g, 'width={size}')
      .replace(/height=\{size\}/g, 'height={size}')
      .replace(/width="\d+"/, 'width={size}')
      .replace(/height="\d+"/, 'height={size}');
    
    // Ensure xmlns is present
    if (!svg.includes('xmlns=')) {
      svg = svg.replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ');
    }
    
    output += `/** ${icon.name} (default size: ${icon.defaultSize}) */
export const ${icon.name} = ({ size = ${icon.defaultSize}, className }: IconProps) => (
  ${svg}
);

`;
  }
  
  await fs.promises.writeFile(OUT, output);
  console.log(`Written to ${OUT}`);
  console.log(`File size: ${output.length} bytes`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
